[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x", "openssl"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = [
    "pnpm install --filter @mularpay/mularpay-api",
    "pnpm --filter @mularpay/mularpay-api prisma:generate",
    "pnpm --filter @mularpay/mularpay-api build"
]

[start]
cmd = "node dist/src/main.js"

